name: Build Docker Image and Push it To ECR and Deploy to ECS
on:
  push:
    branches:
      - main
      
jobs:
  build_and_push_to_ECR:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check current work directory
    - run: |
        echo Checking current work directory. It is important since docker must be run from project root directory && \
        pwd

    - name: Build docker
      run: |
        docker buildx build --platform=linux/amd64 -t devops15/workflow-service

    - name: Docker Retag
      run: |
        docker tag devops15/workflow-service:latest 314146339425.dkr.ecr.eu-central-1.amazonaws.com/devops15/workflow-service:latest

    - name: AWS Login
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TO_PROJ }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TO_PROJ }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN_TO_PROJ }}
        aws-region: eu-central-1
        audience: sts.amazonaws.com

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 314146339425.dkr.ecr.eu-central-1.amazonaws.com
        
    - name: Push Docker Image
      run : |
        docker push 314146339425.dkr.ecr.eu-central-1.amazonaws.com/devops15/workflow-service:latest
